name: Frontend CI/CD
on: 
  push:
    branches:
      - "merge-sprint2"
      - "fix/testando-ci-cd"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('mega-plate/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
        working-directory: ./mega-plate
      
      - name: Build project
        run: npm run build
        working-directory: ./mega-plate
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: front-build
          path: ./mega-plate/dist

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout again
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: front-build
          path: ./build

      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./build/*"
          target: "/home/${{ secrets.EC2_USER }}/frontend-build"
          strip_components: 1
          overwrite: true

      - name: Move files and restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/frontend-build/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            rm -rf /home/ubuntu/frontend-build
            sudo systemctl restart nginx
            echo "Deploy concluído com sucesso!"